name: Burndown Chart

on: [push]  # 触发条件，这里示例为每次代码推送时

jobs:
  build:
    runs-on: ubuntu-latest  # 运行环境

    steps:
    - uses: actions/checkout@v2  # 检出代码

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # 设置Node.js版本

    - name: Install dependencies
      run: npm install  # 安装依赖

    - name: Generate Burndown Chart
      run: npm run-script generate-burndown  # 运行脚本生成燃尽图，需要你项目中有相应的脚本

    - name: Upload Burndown Chart
    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: dist/
