name: Burndown Chart

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm install burndown-js
    - run: node_modules/.bin/burndown-js -i issues -o burndown.png
    - uses: actions/upload-artifact@v2
      with:
        name: burndown-chart
        path: burndown.png
