name: Build and Upload Burndown Chart

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # 明确指定 Node.js 16 版本

    - name: Install dependencies
      run: npm install

    - name: Generate Burndown Chart
      run: npm run-script generate-burndown

    - name: Upload Burndown Chart
      uses: actions/upload-artifact@v3
      with:
        name: burndown-chart
        path: path/to/burndown-chart.png
